name: open_meteo_api
description: A Dart API Client for the Open-Meteo API.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  build_runner: ^2.4.11
  http: ^1.2.2
  json_annotation: ^4.6.0
  json_serializable: ^6.8.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.16.4